name: publish Storybook
on:
  push:
    branches:
      - 'main'
jobs:
  publish:
    if: github.repository == 'freee/vibes'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: ${{ secrets.PROD_AWS_ROLE_TO_ASSUME }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Build Storybook
        run: npm run build-storybook
      - name: Publish to S3
        env:
          AWS_BUCKET: ${{ secrets.PROD_AWS_S3_BUCKET }}
        run: aws s3 sync --delete ${GITHUB_WORKSPACE}/storybook-static/ s3://${AWS_BUCKET}/ --quiet
